version: '3.8'

services:
  # MySQL Databases
  db:
    image: mysql:8.0
    container_name: storerater-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aniket_52kr_2004
      MYSQL_DATABASE: storerater_db
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network


  # Backend API 
  backend: 
    # build: ./backend 
    image: aniket52kr/storerater-backend:latest
    container_name: storerater-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: storerater_db
      JWT_SECRET: 512cf4a6d5e792e70d97672dee067ec6
    ports:
      - "5000:5000"
    depends_on:
      - db 
    networks:
      - app-network 


  # Frontend React App
  frontend: 
    # build: ./frontend
    image: aniket52kr/storerater-frontend:latest
    container_name: storerater-frontend
    restart: unless-stopped 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network 
    

# Names volume for persistent data
volumes:
  db_data:


# custom networks
networks:
  app-network: 
    driver: bridge

